server:
  port: 8183

spring:
  application:
    name: user
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  pattern.console: '%white([%thread]) %highlight(%-5level) %cyan(%logger{5}) %magenta([%file:%-4L]) - %msg%n'
  level:
    root: INFO
