server:
  port: 8082

spring:
  application:
    name: editor
  data:
    mongodb:
      host: localhost
      port: 27017
      database: editor

logging:
  pattern.console: '%white([%thread]) %highlight(%-5level) %cyan(%logger{5}) %magenta([%file:%-4L]) - %msg%n'
  level:
    root: INFO
